### PR TITLE
Fixed: Default region is undefined

### PR DESCRIPTION
**Pull request by MuratUrsavas**
**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Review by KevinWassermann94 — APPROVED** [review]

**Comment by shawaj** [comment]
@MuratUrsavas why do we need awk anyway?

I think they changed it so that the default returns UNKNOWN now so we don't need this.

See #38

**Comment by MuratUrsavas** [comment]
@shawaj They started to return `null` at some point. And it was different before. I thought something should be wrong.

So is it `null` or `UNKNOWN`? It's safe to implement both, though.

**Comment by shawaj** [comment]
@MuratUrsavas why not even simpler then, like this? https://github.com/NebraLtd/hm-gatewayrs/pull/46

**Comment by MuratUrsavas** [comment]
@shawaj was thinking the same because somehow weirdly it sometimes return empty, too.

**Pull request merged**
